services:
  mongodb1:
    container_name: mongodb1
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: john
      MONGO_INITDB_DATABASE: admin 
    volumes:
      - "./data-mongo1:/data/db"