services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: john
      MONGO_INITDB_DATABASE: admin 
  mongodb-expres-example:
    container_name: mongodb-expres-example
    image: mongo-express:latest
    depends_on:
      - mongodb-example
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: john
      ME_CONFIG_MONGODB_ADMINPASSWORD: john
      ME_CONFIG_MONGODB_SERVER: mongodb-example 
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge