services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: john
      MONGO_INITDB_ROOT_PASSWORD: john
      MONGO_INITDB_DATABASE: admin 